* Introduction

This Org Babel implementation is aimed to people who like tinkering with TeX.

* Examples

See [[file:./examples.org]].

* Supported header arguments


** =:documentclass=

Allowed value: string.

A string that is used after =\documentclass=.

This header argument only has effect when =expand= is set to =yes=.

** =:preamble=

Allowed value: string.

string that is located after the =\documentclass= and before the =document= environment.

This header argument only has effect when =expand= is set to =yes=.

** =:usepackage=

Allowed value: List of strings.

It defines the packages that are included in the file.

This header argument only has effect when =expand= is set to =yes=.

** =:environment=

Allowed value: string.

This header argument sets the environment that is used to enclose the content of the code block.

This header argument only has effect when =expand= is set to =yes=.

** =:expand=

Allowed values: =yes= and =no=

If =yes=, the header arguments =documentclass=, =preamble=, =usepackage=,  and =environment= are used. If =no=, those header arguments are not used.

** =:build-command=

Allowed value: List of lists of strings.

Defines the compilation steps for compiling the document.

Example: =:build-command '(("pdflatex" jobname) ("bibtex" jobname) ("pdflatex" jobname) ("pdflatex" jobname))=

** =:tangle-build-command=

Allowed values: =yes= and =no=

Determines whether a comment with compilation instructions need to be included in the tangled file.

** =:keep-files=

Allowed values: List of regular expressions

Determines which files are not deleted when cleaning the temporary directory where the compilation occurs.

** =:prologue= and =:epilogue=

These header arguments is documented in the Org Mode info manual in the section "Inserting headers and footers".
